import { ItemProps } from "@/types/route-data";
export type serviceType = "PICKUP" | "DROPOFF";

// Generate 5 companies
export const companies = [
  {
    id: "1",
    name: "WTH Car rental ULC",
    phone: "9848898488",
    mobile: "9588849933",
    notes: "lorem ipsum",
    address: "24 Jackson Avenue Kitchener, ON, N2H 3N8",
  },
  {
    id: "2",
    name: "ABC Auto Rentals",
    phone: "9999888777",
    mobile: "9595959595",
    notes: "Reliable rental service",
    address: "56 Elm Street Waterloo, ON, N2L 4J5",
  },
  {
    id: "3",
    name: "Speedy Wheels Rentals",
    phone: "9933888222",
    mobile: "9483848383",
    notes: "Fast and efficient service",
    address: "123 Main Street Cambridge, ON, N1R 1J2",
  },
  {
    id: "4",
    name: "Prime Car Hire",
    phone: "9777888899",
    mobile: "9494949494",
    notes: "Wide selection of vehicles",
    address: "89 King Street London, ON, N6A 1G7",
  },
  {
    id: "5",
    name: "Express Rent-A-Car",
    phone: "9888777666",
    mobile: "9373737373",
    notes: "Convenient location, great prices",
    address: "432 Queen Street Toronto, ON, M5V 2A1",
  },
];

// Generate 10 vehicles linked to the companies
export const vehiclesData = [
  {
    id: "1",
    make: "Mitsubishi",
    model: "Lancer",
    year: "2011",
    vin: "AJ283241",
    type: "PICKUP",
    companyId: "1",
    attachments: [],
  },
  {
    id: "2",
    make: "Toyota",
    model: "Corolla",
    year: "2015",
    vin: "BC394058",
    type: "DROPOFF",
    companyId: "1",
    attachments: [],
  },
  {
    id: "3",
    make: "Honda",
    model: "Civic",
    year: "2017",
    vin: "CD492032",
    type: "PICKUP",
    companyId: "2",
    attachments: [],
  },
  {
    id: "4",
    make: "Ford",
    model: "Focus",
    year: "2018",
    vin: "EF540130",
    type: "DROPOFF",
    companyId: "2",
    attachments: [],
  },
  {
    id: "5",
    make: "Chevrolet",
    model: "Cruze",
    year: "2019",
    vin: "GH612451",
    type: "PICKUP",
    companyId: "3",
    attachments: [],
  },
  {
    id: "6",
    make: "BMW",
    model: "320i",
    year: "2020",
    vin: "IJ785642",
    type: "DROPOFF",
    companyId: "3",
    attachments: [],
  },
  {
    id: "7",
    make: "Audi",
    model: "A3",
    year: "2021",
    vin: "KL829764",
    type: "PICKUP",
    companyId: "4",
    attachments: [],
  },
  {
    id: "8",
    make: "Mercedes-Benz",
    model: "C-Class",
    year: "2021",
    vin: "LM924783",
    type: "DROPOFF",
    companyId: "4",
    attachments: [],
  },
  {
    id: "9",
    make: "Hyundai",
    model: "Elantra",
    year: "2020",
    vin: "MN184920",
    type: "PICKUP",
    companyId: "5",
    attachments: [],
  },
  {
    id: "10",
    make: "Nissan",
    model: "Sentra",
    year: "2022",
    vin: "OP274963",
    type: "DROPOFF",
    companyId: "5",
    attachments: [],
  },
];

export const routesData: ItemProps[] = [
  {
    id: "1",
    companyName: "WTH Car rental ulc",
    vin: "AJ283241",
    type: "PICKUP",
    address: "24 Jackson Ave, Kitchener, ON N2H 2N8",
    status: "COMPLETED",
  },
  {
    id: "2",
    companyName: "east gta compound",
    vin: "KA632881",
    type: "DROP-OFF",
    address: "196 Woodbine Ave, Kitchener, ON, N2R 1Y5",
    status: "DROP-OFF",
  },
  {
    id: "3",
    companyName: "WTH Car rental ulc",
    vin: "AJ283241",
    type: "DROP-OFF",
    address: "24 Jackson Ave, Kitchener, ON N2H 2N8",
    status: "TRANSIT",
  },
  {
    id: "4",
    companyName: "WTH Car rental ulc",
    vin: "AJ283241",
    type: "DROP-OFF",
    address: "24 Jackson Ave, Kitchener, ON N2H 2N8",
    status: "PICKUP",
  },
  {
    id: "5",
    companyName: "WTH Car rental ulc",
    vin: "AJ283241",
    type: "DROP-OFF",
    address: "24 Jackson Ave, Kitchener, ON N2H 2N8",
    status: "DROP-OFF",
  },
];
